export const PLATFORMS = [
  "Github",
  "Frontend Mentor",
  "LinkedIn",
  "Twitter",
  "YouTube",
  "Facebook",
  "Twitch",
  "Dev.to",
  "Codewars",
  "Codepen",
  "freeCodeCamp",
  "GitLab",
  "Hashnode",
  "Stack Overflow",
] as const;
